### ISSUE TITLE
Add minimum replies

### ISSUE THREAD

**Issue by jsjoeio** [sw-yx/bettertwitter#5]
![image](https://user-images.githubusercontent.com/3806031/136669875-a133dacb-2b75-4dbc-8acf-ad8838ddff3b.png)

Example of what it translates to in the search: `(from:dabit3) min_replies:20 since:2021-09-01`

![image](https://user-images.githubusercontent.com/3806031/136669912-ab42e361-8cc3-4b62-9f0f-0786b93adda1.png)

**Comment by swyxio** [comment]
TIL that's a thing!
